# Generated by Django 4.2.29 on 2026-04-26 06:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpds_datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params_json', models.JSONField(default=dict, verbose_name='预处理参数')),
                ('summary_json', models.JSONField(default=dict, verbose_name='预处理摘要')),
                ('output_path', models.CharField(blank=True, max_length=500, verbose_name='输出文件路径')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocess_results', to='dpds_datasets.dataset')),
            ],
            options={
                'verbose_name': '预处理结果',
                'db_table': 'dpds_preprocess_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
