# Generated by Django 4.2.29 on 2026-04-26 06:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpds_datasets', '0001_initial'),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clean_dataset_path', models.CharField(blank=True, max_length=500, verbose_name='净化数据集路径')),
                ('strategy_json', models.JSONField(default=dict, verbose_name='处理策略')),
                ('removed_count', models.IntegerField(default=0, verbose_name='删除样本数')),
                ('relabel_count', models.IntegerField(default=0, verbose_name='重新标注样本数')),
                ('ignored_count', models.IntegerField(default=0, verbose_name='忽略样本数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_results', to='dpds_datasets.dataset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_results', to='detection.detectiontask')),
            ],
            options={
                'verbose_name': '净化结果',
                'db_table': 'dpds_clean_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
