# Generated by Django 4.2.29 on 2026-05-06 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0003_detectionresult_metric_detail_and_more'),
        ('defense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseSampleAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('remove', '删除'), ('relabel', '重新标注'), ('ignore', '忽略'), ('confirm_poison', '确认投毒'), ('mark_clean', '标记为正常')], max_length=20, verbose_name='操作')),
                ('original_label', models.CharField(blank=True, max_length=200, verbose_name='原始标签')),
                ('corrected_label', models.CharField(blank=True, max_length=200, verbose_name='修正标签')),
                ('reason', models.TextField(blank=True, verbose_name='操作理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clean_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_actions', to='defense.cleanresult')),
                ('detection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_actions', to='detection.detectionresult')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '样本复查操作',
                'db_table': 'dpds_defense_sample_action',
                'ordering': ['-created_at'],
            },
        ),
    ]
