# Generated by Django 4.2.29 on 2026-04-26 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '退出'), ('upload', '上传数据集'), ('delete', '删除'), ('detect', '创建检测任务'), ('defense', '执行无害化'), ('export', '导出/下载'), ('config', '修改配置'), ('other', '其他')], max_length=30, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='目标 ID')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'dpds_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
