# Generated by Django 4.2.29 on 2026-04-26 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('html', 'HTML 报告'), ('markdown', 'Markdown 报告'), ('json', 'JSON 报告')], default='html', max_length=20, verbose_name='报告类型')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='报告文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='detection.detectiontask')),
            ],
            options={
                'verbose_name': '检测报告',
                'db_table': 'dpds_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
