# Generated by Django 4.2.29 on 2026-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='analysis_json',
            field=models.JSONField(blank=True, default=dict, help_text='报告使用的统计数据（风险分布、检测器统计等）', verbose_name='分析数据'),
        ),
        migrations.AddField(
            model_name='report',
            name='llm_content',
            field=models.TextField(blank=True, help_text='DeepSeek 生成的专业分析报告', verbose_name='LLM 生成内容'),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, help_text='检测结果的简要总结', verbose_name='报告摘要'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='报告标题'),
        ),
    ]
