# Generated by Django 4.2.29 on 2026-04-26 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpds_datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detector_name', models.CharField(max_length=100, unique=True, verbose_name='检测器名称')),
                ('detector_type', models.CharField(max_length=50, verbose_name='检测器类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('default_params', models.JSONField(default=dict, verbose_name='默认参数')),
                ('weight', models.FloatField(default=0.25, verbose_name='融合权重')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '算法配置',
                'verbose_name_plural': '算法配置',
                'db_table': 'dpds_algorithm_config',
            },
        ),
        migrations.CreateModel(
            name='DetectionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='任务编号')),
                ('detector_config', models.JSONField(default=dict, verbose_name='检测器配置')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='queued', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度 0-100')),
                ('risk_score', models.FloatField(blank=True, null=True, verbose_name='综合风险分数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('baseline_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_for_tasks', to='dpds_datasets.dataset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpds_detection_tasks', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_tasks', to='dpds_datasets.dataset')),
            ],
            options={
                'verbose_name': '检测任务',
                'verbose_name_plural': '检测任务',
                'db_table': 'dpds_detection_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=50, verbose_name='样本标识')),
                ('risk_type', models.CharField(choices=[('label_poison', '标签投毒'), ('backdoor', '后门攻击'), ('distribution_shift', '分布偏移'), ('anomaly', '异常样本'), ('unknown', '未知')], max_length=30, verbose_name='风险类型')),
                ('confidence', models.FloatField(verbose_name='置信度 0-1')),
                ('suggestion', models.CharField(choices=[('remove', '建议删除'), ('relabel', '建议重新标注'), ('ignore', '忽略'), ('review', '人工复查')], default='review', max_length=20, verbose_name='处理建议')),
                ('detector_name', models.CharField(max_length=100, verbose_name='检测器名称')),
                ('detail_doc_id', models.CharField(blank=True, max_length=50, verbose_name='MongoDB 文档 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detection.detectiontask')),
            ],
            options={
                'verbose_name': '检测结果',
                'db_table': 'dpds_detection_result',
                'ordering': ['-confidence'],
            },
        ),
    ]
