# Generated by Django 4.2.29 on 2026-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmconfig',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='显示名称'),
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='requires_baseline',
            field=models.BooleanField(default=False, verbose_name='需要基准数据集'),
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='supported_dataset_types',
            field=models.JSONField(blank=True, default=list, verbose_name='支持的数据集类型'),
        ),
    ]
