# Generated by Django 4.2.29 on 2026-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_add_detector_display_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='metric_detail',
            field=models.JSONField(blank=True, default=dict, help_text='检测算法输出的中间指标', verbose_name='指标详情'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='processed_data_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='该样本经过预处理后的字段值', verbose_name='处理后数据快照'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='raw_data_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='该样本在原始数据集中的字段值', verbose_name='原始数据快照'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='reason',
            field=models.TextField(blank=True, help_text='检测器给出的自然语言解释', verbose_name='判定原因'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='triggered_features',
            field=models.JSONField(blank=True, default=list, help_text='触发检测的特征列表，如异常词、异常值等', verbose_name='触发特征'),
        ),
    ]
